---

- name: Check if GOlang binary exists.
  stat:
    path: "/usr/local/go/bin/go"
  register: golang_check
  
- name: Check golang version.
  command: "/usr/local/go/bin/go version"
  failed_when: false
  changed_when: false
  register: golang_existing_version
  
- name: Download GOlang binary
  get_url:
    url: https://go.dev/dl/go{{ golang_version }}.linux-amd64.tar.gz
    dest: /tmp
    owner: root
    group: root
    mode: 0755
  register: golang_download
  when: >
    not golang_check.stat.exists
    or golang_version not in golang_existing_version.stdout

- name: Unarchive GOlang
  ansible.builtin.unarchive:
    src: /tmp/go{{ golang_version }}.linux-amd64.tar.gz
    dest: /usr/local
    remote_src: yes
  when: golang_download is changed
    
- name: Set GOlang PATH
  command: >-
    echo 'export PATH=/usr/local/go/bin:${PATH}' |
      sudo tee /etc/profile.d/go.sh
  args:
    creates: /etc/profile.d/go.sh
  changed_when: true
  when: >
    not golang_check.stat.exists
    or golang_version not in golang_existing_version.stdout