---
- name: Create role_dir directory
  file:
    path: "{{ proxmox_terraform_role_dir }}"
    state: directory
    owner: root
    group: root
    mode: 0700
    recurse: yes

- name: Create main.tf
  ansible.builtin.template:
    src: main.tf.j2
    dest: "{{ proxmox_terraform_role_dir }}/main.tf"
    owner: root
    group: root
    mode: '0600'
- name: Terraform Plan
  community.general.terraform:
    project_path: "{{ proxmox_terraform_role_dir }}"
    plan_file: "{{ proxmox_terraform_role_dir }}/tfplan"
    force_init: true
    state: planned
  environment:
    PM_USER: "{{ proxmox_terraform_user }}"
    PM_PASS: "{{ proxmox_terraform_password }}"
- name: Parse Plan
  ansible.builtin.command: 
    chdir: "{{ proxmox_terraform_role_dir }}"
    cmd: "terraform show -no-color -json tfplan| jq -M .resource_changes[0].change > change"
- name: Store changes before
  ansible.builtin.command: 
    chdir: "{{ proxmox_terraform_role_dir }}"
    cmd: "jq -M .before change > change.before"
- name: Store changes after
  ansible.builtin.command: 
    chdir: "{{ proxmox_terraform_role_dir }}"
    cmd: "jq -M .after change > change.after"
- name: Parse Plan
  ansible.builtin.command: 
    chdir: "{{ proxmox_terraform_role_dir }}"
    cmd: "jd change.before change.after"
  register: plandiff
- name: Print Plan
  debug: 
    var: plandiff.stdout
- name: Terraform apply
  community.general.terraform:
    project_path: "{{ proxmox_terraform_role_dir }}"
    plan_file: "{{ proxmox_terraform_role_dir }}/tfplan"
    force_init: true
    state: present
  environment:
    PM_USER: "{{ proxmox_terraform_user }}"
    PM_PASS: "{{ proxmox_terraform_password }}"