---
- name: Check if flux binary exists.
  stat:
    path: "{{ flux_bin_path }}"
  register: flux_check

- name: Check flux version.
  command: "{{ flux_bin_path }} -v"
  failed_when: false
  changed_when: false
  register: flux_existing_version
  
- name: Download flux-installer
  ansible.builtin.get_url:
    url: "{{ flux_install_script }}"
    dest: /tmp/flux-install.sh
    mode: '0700'
  register: flux_download
  when: >
    not flux_check.stat.exists
    
- name: Run installer
  ansible.builtin.shell:
    cmd: ./flux-install.sh
    chdir: /tmp/
    creates: "{{ flux_bin_path }}"
  become: true
  when: not flux_download is skipped
    
- name: remove installer
  ansible.builtin.file:
    path: /tmp/flux-install.sh
    state: absent
  when: not flux_download is skipped
