- name: Create elastic namespace
  kubernetes.core.k8s:
    name: elastic
    api_version: v1
    kind: Namespace
    state: present
    
- name: Deploy elastic-master-password secret inside elastic namespace
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: elasticsearch-master-credentials
        namespace: elastic
      stringData:
        username: elastic
        password: "{{ base_password }}"
      type: Opaque

- name: Create Internal Elastic Certificate
  kubernetes.core.k8s:
    state: present
    template:
      path: 'elastic-cert.yaml'

- name: Create Transport Trust for Internal Certificate
  kubernetes.core.k8s:
    state: present
    template:
      path: 'elastic-transport.yaml'
      
- name: Create kibana encryption key Secret
  kubernetes.core.k8s:
    state: present
    template:
      path: 'kibana-encryption.yaml.j2'

- name: Add Elastic chart repo
  kubernetes.core.helm_repository:
    name: elastic
    repo_url: "https://helm.elastic.co"

- name: Deploy latest version of elasticsearch chart inside elastic namespace
  kubernetes.core.helm:
    name: elasticsearch
    chart_ref: elastic/elasticsearch
    release_namespace: elastic
    values: "{{ lookup('template', 'elastic-values.yaml.j2') | from_yaml }}"
    
- name: "wait for elastic to come online"
  ansible.builtin.uri:
    url: "https://{{ elasticsearch_hostname }}/_cluster/health"
    url_username: elastic
    url_password: "{{ base_password }}"
    status_code: 200
    validate_certs: false
  register: result
  until: result.status == 200 
  retries: 60
  delay: 5
  
- name: Deploy latest version of kibana chart inside elastic namespace
  kubernetes.core.helm:
    name: kibana
    chart_ref: elastic/kibana
    release_namespace: elastic
    values: "{{ lookup('template', 'kibana-values.yaml.j2') | from_yaml }}"

- name: Deploy latest version of apm-server chart inside elastic namespace
  kubernetes.core.helm:
    name: apm-server
    chart_ref: elastic/apm-server
    release_namespace: elastic
    values: "{{ lookup('template', 'apm-values.yaml.j2') | from_yaml }}"