---
- name: Add pkgs.k8s.io apt signing key
  ansible.builtin.apt_key:
    url: https://pkgs.k8s.io/core:/stable:/{{ kubernetes_version | regex_search('v[0-9]+\.[0-9]+') }}/deb/Release.key
    state: present
    
- name: somerepo | apt source
  ansible.builtin.apt_repository:
    repo: deb https://pkgs.k8s.io/core:/stable:/{{ kubernetes_version | regex_search('v[0-9]+\.[0-9]+') }}/deb/ /
    state: present

- name: Update repositories cache and install kubernetes packages
  ansible.builtin.apt:
    pkg:
    - kubelet
    - kubeadm
    - kubectl
    update_cache: yes
    
- name: Hold kubeadm
  ansible.builtin.dpkg_selections:
    name: "{{ item }}"
    selection: hold
  loop:
    - 'kubelet'
    - 'kubeadm'
    - 'kubectl'
    
- name: Disabling swap
  shell: "swapoff --all"
  become: true

- name: Disable swap permanently
  ansible.posix.mount:
    name: "{{ item }}"
    fstype: swap
    state: absent
  loop: ["none", "swap"]
  
- name: Run installer
  ansible.builtin.shell:
    cmd: crictl config --set runtime-endpoint=unix:///run/containerd/containerd.sock
    chdir: /tmp/
    creates: "/etc/crictl.yaml"
  become: true
  when: not flux_download is skipped