---
- name: Install pip packages
  ansible.builtin.apt:
    pkg:
    - python3-pip
    cache_valid_time: 3600
- name: Install kubernetes and openshift packages
  ansible.builtin.pip:
    name:
    - kubernetes
    - openshift
    executable: pip3
    